config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/post'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'post' => 'static_pages#post'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
  default_scope -> { order(created_at: :asc) }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [ :create, :destroy]
  before_action :correct_user, only: :destroy

	def create
    @micropost = Micropost.find(params[:comment][:micropost_id])
  	@comment = @micropost.comments.build(comment_params)
    if @comment.save
      respond_to do |format|
      format.html { redirect_to @micropost }
      format.js
    end
    else
      flash[:alert] = "Cann't create comment"
      redirect_to @micropost
    end
  end

  def destroy
    @micropost = @comment.micropost
    if @comment.destroy
      respond_to do |format|
      format.html { redirect_to @micropost }
      format.js
    end
    else
      flash[:alert] = "Cann't delete this comment"
      redirect_to @micropost
    end 
  end

  def edit
    @comment = Comment.find(params[:id])
    @micropost = @comment.micropost
    @user = @comment.user
  end

  def update
    @comment = Comment.find(params[:id])
    @micropost = @comment.micropost
    if !@comment.update(comment_params)
      flash[:alert] = "Cann't edit comment"
      redirect_to @micropost
    else
      flash[:success] = "Updated comment"
      redirect_to @micropost
    end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:content, :user_id)
  	end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <span class="content">
    <%= comment.content %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
    <% if current_user?(comment.user) %>
    <div class="btn-group">
      <button type="button" class="btn btn-sm">Edit</button>
      <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Edit", edit_comment_path(comment) %></li>
        <li><%= link_to "Delete", comment, method: :delete, data: { confirm: "You sure"} %></li>
      </ul>
    </div>
    <% end %>
  </span>
</li>

app/views/comments/create.js.erb
$("#comment_id").prepend("<%= escape_javascript(render('comments/prepend_comment')) %>");
$("#comment-text-field-id").val('');

app/views/comments/destroy.js.erb
$("#comment_form").html("<%= escape_javascript(render('microposts/show')) %>");

app/views/comments/edit.html.erb
<% provide(:title, "Edit comment") %>
<h1>Edit comment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@comment) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :user_id, value: current_user.id %>
  		<%= f.hidden_field :micropost_id,  value: @micropost.id %>

      <%= f.label :content, "Content" %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>